<a href="https://colab.research.google.com/github/Dhanasree-Rajamani/Deep_Learning_Assignments/blob/main/Assignment_2b/DL_Numpy_einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Statements

In [22]:
import numpy as np
import torch.nn.functional as F

Experimenting Basics with eisum and pytorch

In [23]:
x = np.random.rand(2, 3)
x

array([[0.94379251, 0.1221907 , 0.40130232],
       [0.65313126, 0.67235375, 0.20983514]])

In [24]:
# Sum

# Full sum
print(np.einsum("ij->", x))

# Row sum
print(np.einsum("ij->i", x))

# Col sum
np.einsum("ij->j", x)

3.0026056807020756
[1.46728553 1.53532015]


array([1.59692377, 0.79454445, 0.61113746])

Matrix Transpose

(Permute)

In [25]:
print(np.einsum("ij -> ji", x))

[[0.94379251 0.65313126]
 [0.1221907  0.67235375]
 [0.40130232 0.20983514]]


Vector vector Multiplication

In [26]:
a = vector = np.array([1,2,3])
b = vector = np.array([2,4,6])

np.einsum("i,i->i",b,a)

array([ 2,  8, 18])

Scalar vector multiplication 

In [27]:
v = [1, 2, 3]
print(np.array(v) * 2)

scalar = np.array([4])
vector = np.array([1, 3, 4])
print(np.einsum('i,j->j', scalar, vector))

[2 4 6]
[ 4 12 16]


Vector Matrix Multiplication

In [28]:
v = np.random.rand(1, 3)
np.einsum("ik,jk->ij", x, v)

array([[1.00162268],
       [0.72213181]])

Matrix multiplication

In [29]:
m = np.random.rand(5, 3)
np.einsum("ik,jk->ij",x, m)

array([[0.84947298, 0.46977078, 0.16866999, 1.16816426, 0.45632088],
       [0.71128571, 0.66445018, 0.37952645, 1.34289925, 0.7576769 ]])

Outer Product

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
np.einsum('i,j->ij', a, b)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]])

Vector Dot product with matrix

In [31]:
vector  = vector = np.array([1,2,3])
matrix = [[1,2,3],[1,2,3]]
np.einsum("i,ji->j", vector, matrix)

array([14, 14])

Hadamard product 

(Element wise multiplication)

In [32]:
mat1 = [[1,2,3],[4,5,6]]
mat2 = [[1,2,3],[4,5,6]]
np.einsum("ij,ij->ij",mat1,mat2)

array([[ 1,  4,  9],
       [16, 25, 36]])

Batch multiplication

In [33]:
a = np.random.rand(3,2,5)
b = np.random.rand(3,5,3)
print(a)
print(b)
np.einsum('ijk,ikl->ijl', a, b)

[[[0.1381754  0.84799407 0.35507865 0.18136643 0.2876896 ]
  [0.01987606 0.3511761  0.80152807 0.2018186  0.36891098]]

 [[0.47453138 0.84592917 0.13896738 0.50691233 0.63162104]
  [0.53285103 0.57687116 0.326619   0.25146489 0.72169859]]

 [[0.06201541 0.65617854 0.33716319 0.17728981 0.77414374]
  [0.25800017 0.17334048 0.08303836 0.48239151 0.56526647]]]
[[[0.70905295 0.10850195 0.00930454]
  [0.87383766 0.39382551 0.74027773]
  [0.82387902 0.64825095 0.60951291]
  [0.06296138 0.01161096 0.15736695]
  [0.92564852 0.76882606 0.82444765]]

 [[0.61128389 0.79783625 0.26325237]
  [0.73169235 0.702343   0.74916791]
  [0.43499614 0.48533957 0.57742729]
  [0.56371118 0.42825192 0.98219453]
  [0.61268294 0.80515098 0.60456455]]

 [[0.66986055 0.98381625 0.07744144]
  [0.8921382  0.02736887 0.19123304]
  [0.54879988 0.15468597 0.21822516]
  [0.31987799 0.62408667 0.43954539]
  [0.54966032 0.93188901 0.15822062]]]


array([[[1.40924322, 0.80242317, 1.1111879 ],
        [1.33551494, 0.94602172, 1.08460187]],

       [[1.64221915, 1.76581362, 1.71865026],
        [1.47381946, 1.67757707, 1.4443472 ]],

       [[1.29420593, 0.9631853 , 0.40427548],
        [0.83805022, 1.09923348, 0.37271916]]])

Tensor reduction

In [34]:
a = np.random.rand(2,17,5,7)
b = np.random.rand(11,2,4,17,6)
np.einsum('pqrs,tpwqm->rstwm', a, b).shape

(5, 7, 11, 4, 6)

Bilinear Transformation

In [35]:
a = np.random.rand(2,3)
b = np.random.rand(5,3,7)
c = np.random.rand(2,7)
np.einsum('ik,jkl,il->ij', a, b, c)

array([[1.58000135, 1.96797809, 2.09936678, 2.30222338, 1.87102663],
       [1.81050054, 1.92971291, 2.28299386, 2.04617278, 1.97232057]])

Random Tensors function

In [36]:
#this function generates and returns a tensors based on the input shape
#num denotes the number of times the loop should run - based on number of variables to assign value to  

#def random_tensors(shape, num=1):
#  return [np.random.randn(*shape) for i in range(num)]

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [np.random.randn(*shape) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors


Attention

In [37]:
#einsum was giving errors so tried a few using matmul 

bM, br, w = random_tensors([7], num=3)
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4)

print(bM, br, w)

print(WY, Wh, Wr, Wt)

def attention(Y, ht, rt1):

  tmp = np.einsum('ik,kl->il', ht, Wh) + np.einsum('ik,kl->il', rt1, Wr)
  
  
  #tanh return a new tensor with the hyperbolic tangent of the given input
  #expand_dims is to get a tensor add insert an additional dimension at the given position  
  Mt = np.tanh(np.matmul(Y, WY) + np.expand_dims(tmp, 1) + bM)

  # -- [batch_size x sequence_length]
  #using this in for softmax in np
  at = np.exp(np.matmul(Mt, w)) / np.sum(np.exp(np.matmul(Mt, w)), axis=1, keepdims=True)
 

  # -- [batch_size x hidden_dimension]
  rt = np.matmul(at[..., None, :], Y).squeeze() + np.tanh(np.matmul(rt1, Wt) + br)
 

  return rt, at

# -- [batch_size x sequence_length x hidden_dimension]
Y = np.array(random_tensors([3, 5, 7]))

# -- [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

print(ht)

print(rt1)

rt, at = attention(Y, ht, rt1)
at  # -- print attention weights


[-0.6819007   0.43336112 -2.03883991  0.0114687   1.84461392  0.47968351
  0.91387846] [ 0.2015608   0.62562457  0.03759612  0.81302335  0.46413719  0.94178213
 -0.8013779 ] [-2.4407867   0.53068681 -1.41396565 -1.12795882 -0.70997584  1.2869481
  0.02497065]
[[-0.28195633  1.61393438 -0.24440706  0.31570991  0.03458595 -1.11733572
  -0.10575867]
 [-0.46877195  0.32483494  1.37876489 -0.52636084 -0.02254524  0.38447757
   1.87200116]
 [ 0.83121289 -0.85009263  1.0173207  -0.69884469 -1.6486079  -0.61609757
  -2.50168515]
 [ 0.37893184  0.11294451 -0.16882021 -0.82400553  0.02151637 -0.89934224
   1.26303614]
 [ 0.1789878  -0.19155248  2.65972595  0.04644652  0.39167864 -1.16829365
  -1.12291493]
 [ 1.66932112  1.198152   -1.70202365 -0.91603993 -0.5679276   0.8733894
   1.43836087]
 [ 1.19026322  1.35835879  1.35523542  0.97052217  0.97788747 -2.05421366
  -0.16803885]] [[ 0.27782728 -2.04679662  0.97005211 -0.09005636  0.74610759 -0.74732875
  -0.98694736]
 [-0.70194707 -0.49926729 -0

array([[1.73830688e-03, 3.63278618e-03, 1.25323959e-02, 9.56519074e-01,
        2.55774372e-02],
       [5.53926423e-04, 9.79844420e-01, 3.23984834e-03, 3.77558200e-04,
        1.59842470e-02],
       [1.49730421e-01, 1.94494973e-01, 1.41224205e-01, 5.71665650e-02,
        4.57383836e-01]])

Tree qn

In [38]:
# Parameters
# -- [num_actions x hidden_dimension]
b = random_tensors([5, 3], requires_grad=True)
# -- [num_actions x hidden_dimension x hidden_dimension]
W = random_tensors([5, 3, 3], requires_grad=True)

print(b)
print(W)

def transition(zl):
  # -- [batch_size x num_actions x hidden_dimension]
  return zl[:, None, :] + np.tanh(np.einsum("bk,aki->bai", zl, W) + b)

# Sampled dummy inputs
# -- [batch_size x hidden_dimension]
zl = random_tensors([2, 3])

print(zl)
transition(zl)

print(zl)

[[-0.6515774   0.74179764 -0.2579887 ]
 [ 1.22666659  1.9171741  -0.79127763]
 [-0.0601294  -0.04169373  0.83955597]
 [ 1.7254171   0.05986703  0.54293899]
 [ 0.0938899  -0.25153015 -0.48148197]]
[[[-1.44090967e+00  4.10222561e-01  1.28542834e-01]
  [ 5.59266375e-01  6.54924695e-01 -7.21228107e-01]
  [-2.02097254e-01  1.72268578e+00 -1.50721038e+00]]

 [[-7.66167300e-01 -2.53442523e-01 -4.80359020e-02]
  [-1.11798570e+00  7.73716664e-01  1.22265308e-01]
  [-2.32109245e-02  1.67416650e-01 -1.90922782e+00]]

 [[ 1.41425719e+00  1.23018113e-02 -6.31021692e-01]
  [ 7.95726754e-02  1.42653792e+00 -5.65525671e-02]
  [ 1.06210576e-01 -6.04073273e-01 -3.15668627e-01]]

 [[-1.38579769e+00 -1.04282195e+00  1.38321387e+00]
  [-1.26221168e+00 -4.47931513e-01 -1.21633968e+00]
  [ 4.66065534e-01  2.59522670e+00  1.09302284e+00]]

 [[ 9.49382537e-02  6.39411566e-01  5.72389287e-01]
  [-7.21495795e-01 -7.48674999e-02 -1.38180871e+00]
  [-3.56065026e-04 -1.52750943e-01 -1.19634272e-01]]]
[[-3.83271558e