<a href="https://colab.research.google.com/github/Dhanasree-Rajamani/Deep_Learning_Assignments/blob/main/Assignment_2b/DL_Pytorch_einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Statements

In [1]:
import torch
import numpy as np
import tensorflow as tf
import torch.nn.functional as F

Experimenting Basics with eisum and pytorch

In [2]:
x = torch.rand((2, 3))
x

tensor([[0.7506, 0.7333, 0.9085],
        [0.3212, 0.3772, 0.9466]])

In [3]:
# Sum

# Full sum
print(torch.einsum("ij->", x))

# Row sum
print(torch.einsum("ij->i", x))

# Col sum
torch.einsum("ij->j", x)

tensor(4.0373)
tensor([2.3923, 1.6450])


tensor([1.0718, 1.1105, 1.8551])

Matrix Transpose

(Permute)

In [4]:
print(torch.einsum("ij -> ji", x))

tensor([[0.7506, 0.3212],
        [0.7333, 0.3772],
        [0.9085, 0.9466]])


Vector vector Multiplication

In [5]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,4,6])

torch.einsum("i,i->i",b,a)

tensor([ 2,  8, 18])

Scalar vector multiplication

In [6]:
vector = torch.Tensor([1, 2, 3, 4, 5])
#by using a scalar tensor
scalar = torch.Tensor([5])

res = torch.einsum("i,i->i",vector,scalar)
print(res)

#using a regular scalar, but not einsum
a= 5
b= torch.tensor([1,2,3,4,5])
print("Scalar vector mul: ",torch.mul(vector, scalar))

tensor([ 5., 10., 15., 20., 25.])
Scalar vector mul:  tensor([ 5., 10., 15., 20., 25.])


Vector Matrix Multiplication

In [7]:
v = torch.rand((1,3))
torch.einsum("ik,jk->ij", x, v)

tensor([[0.8207],
        [0.8190]])

Matrix multiplication

In [8]:
m = torch.rand((5,3))
torch.einsum("ik,jk->ij",x, m)

tensor([[1.2185, 1.1115, 1.3639, 1.4635, 0.7980],
        [0.9581, 1.0158, 0.8738, 1.1318, 0.7455]])

Outer Product

In [9]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6,7])
torch.einsum('i,j->ij', [a, b])

tensor([[ 4,  5,  6,  7],
        [ 8, 10, 12, 14],
        [12, 15, 18, 21]])

Vector Dot product with matrix

In [10]:
vector  = torch.tensor([1,2,3])
matrix = torch.tensor([[1,2,3],[1,2,3]])
torch.einsum("i,ji->j", vector, matrix)

tensor([14, 14])

Hadamard product 

(Element wise multiplication)

In [11]:
mat1 = torch.tensor([[1,2,3],[4,5,6]])
mat2 = torch.tensor([[1,2,3],[4,5,6]])
torch.einsum("ij,ij->ij",mat1,mat2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

Batch multiplication

In [12]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
print(a)
print(b)
torch.einsum('ijk,ikl->ijl', [a, b])

tensor([[[ 0.8646, -0.5582,  0.8201,  1.3421, -1.4749],
         [-1.5393,  0.9165,  0.6591, -0.4621, -0.2293]],

        [[ 1.1693, -2.2040, -0.1950,  1.2123, -1.5279],
         [ 0.8987, -0.8501,  0.4874,  0.5478, -0.7393]],

        [[ 0.1098, -1.1359,  0.3085, -1.7176,  0.7358],
         [ 1.4021,  2.3415, -0.6526, -0.9761,  1.2569]]])
tensor([[[ 0.5439, -0.9442, -1.6123],
         [ 1.7300, -0.8881, -0.8386],
         [ 0.0410,  0.5858, -0.0166],
         [ 0.7151,  0.1271, -2.5635],
         [-1.3893, -0.1532,  0.2334]],

        [[ 0.4666,  1.1202, -0.2598],
         [ 2.1717, -0.3175,  0.1242],
         [-0.7934, -0.0903, -0.2720],
         [-0.1763, -1.2716,  0.9953],
         [ 0.3235,  2.1221, -0.6791]],

        [[ 0.1446,  0.9419,  0.3606],
         [ 0.6822, -0.3792, -0.0113],
         [ 0.0216, -0.3186,  0.2016],
         [ 0.1134, -0.8608,  0.6118],
         [-0.2093,  0.5927, -0.1613]]])


tensor([[[ 2.5472,  0.5563, -4.7243],
         [ 0.7634,  1.0019,  2.8334]],

        [[-4.7942, -2.7569,  1.7196],
         [-2.1493, -1.0328,  0.5755]],

        [[-1.1012,  2.3504, -1.0549],
         [ 1.4123,  2.2259, -0.4524]]])

Tensor reduction

In [13]:
a = torch.randn(2,17,5,7)
b = torch.randn(11,2,4,17,6)


torch.einsum('pqrs,tpwqm->rstwm', [a, b]).shape

torch.Size([5, 7, 11, 4, 6])

Bilinear Transformation

In [14]:
a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
torch.einsum('ik,jkl,il->ij', [a, b, c])

tensor([[ -4.1781,   2.9073,   8.2352, -11.7879,  -3.1569],
        [ -2.3658,  -3.2720,  17.6204, -16.3037,   5.9743]])

Attention

Random tensors function

In [15]:
#this function generates and returns a tensors based on the input shape
#num denotes the number of times the loop should run - based on number of variables to assign value to  
def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

In [16]:
# Parameters
# -- [hidden_dimension]

#requires_grad is to tell autograd to begin recording operations on a Tensor tensor
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# -- [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

print(bM, br, w)

print(WY, Wh, Wr, Wt)


def attention(Y, ht, rt1):
  # -- [batch_size x hidden_dimension] 
  tmp = torch.einsum("ik,kl->il", [ht, Wh]) + torch.einsum("ik,kl->il", [rt1, Wr])

  #tanh return a new tensor with the hyperbolic tangent of the given input
  #unsqueeze is to get a tensor add insert an additional dimension at the given position
  Mt = F.tanh(torch.einsum("ijk,kl->ijl", [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # -- [batch_size x sequence_length]
  #applying softmax : expression/sigma expression
  at = F.softmax(torch.einsum("ijk,k->ij", [Mt, w])) 
  
  # -- [batch_size x hidden_dimension]
  rt = torch.einsum("ijk,ij->ik", [Y, at]) + F.tanh(torch.einsum("ij,jk->ik", [rt1, Wt]) + br)
  
  # -- [batch_size x hidden_dimension], [batch_size x sequence_dimension]
  return rt, at

# Sampled dummy inputs
# -- [batch_size x sequence_length x hidden_dimension]
Y = random_tensors([3, 5, 7])
# -- [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

print(ht)

print(rt1)

rt, at = attention(Y, ht, rt1)
at  # -- print attention weights

tensor([ 0.6063,  0.8276, -0.2791,  0.5231, -0.8865,  0.8677, -2.0890],
       requires_grad=True) tensor([-1.4747, -0.5452,  0.6770,  0.2005, -0.3470, -0.3761,  0.2864],
       requires_grad=True) tensor([-0.9051, -1.3016, -0.0436,  0.9378, -1.1669, -0.4897,  0.1494],
       requires_grad=True)
tensor([[ 0.8804, -1.2171,  1.0579, -0.3152, -0.2339,  0.9203,  0.8639],
        [ 0.0395, -0.6074,  0.8616,  1.4354, -0.9257, -0.6261,  0.6885],
        [ 0.7136, -0.1668,  0.1346, -0.5040, -0.4708, -0.1130,  0.2277],
        [ 0.3450, -0.5538, -1.0206,  0.6619,  1.5091,  1.5177, -0.6255],
        [-1.1667,  0.2109, -0.2933,  0.5192,  0.7864, -0.3015,  0.4956],
        [-0.5215, -1.6504,  0.9887,  0.4435, -0.5634,  1.0736, -1.6727],
        [-0.2853,  0.1680, -1.1446,  0.2012,  0.9796, -0.7681, -0.5591]],
       requires_grad=True) tensor([[-0.9851, -0.6977, -0.3381, -1.9434,  1.2185,  0.9177,  0.7909],
        [ 0.0137,  1.3459,  0.1543,  3.2149, -2.1357, -0.4277,  0.2995],
        [-1.5983, 

/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
<ipython-input-16-523ad4c47204>:24: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = F.softmax(torch.einsum("ijk,k->ij", [Mt, w]))


tensor([[0.0667, 0.0777, 0.0432, 0.8069, 0.0057],
        [0.0535, 0.5501, 0.1257, 0.0586, 0.2120],
        [0.0632, 0.1220, 0.2805, 0.3449, 0.1894]], grad_fn=<SoftmaxBackward0>)

Tree Qn

In [17]:
# Parameters
# -- [num_actions x hidden_dimension]
b = random_tensors([5, 3], requires_grad=True)
# -- [num_actions x hidden_dimension x hidden_dimension]
W = random_tensors([5, 3, 3], requires_grad=True)

print(b)
print(W)

def transition(zl):
  # -- [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + F.tanh(torch.einsum("bk,aki->bai", [zl, W]) + b)

# Sampled dummy inputs
# -- [batch_size x hidden_dimension]
zl = random_tensors([2, 3])

print(zl)
transition(zl)

print(zl)

tensor([[-0.8576, -2.3004,  2.2165],
        [ 1.8808,  0.1042, -0.3352],
        [ 0.9317, -0.2656, -2.5995],
        [ 1.5995, -0.2984, -0.0563],
        [ 2.2318,  0.1245,  0.9341]], requires_grad=True)
tensor([[[-0.3914, -1.4093,  1.1725],
         [ 0.1884,  1.8752,  0.1290],
         [ 0.5926,  1.5598, -1.2532]],

        [[-0.7844,  0.1997,  0.5245],
         [ 0.7051,  0.7116, -0.0075],
         [ 1.8331, -0.8990, -0.4586]],

        [[ 1.0734,  0.6890,  1.1198],
         [ 0.6032, -0.2517, -1.7760],
         [ 0.4344,  0.5344, -0.4255]],

        [[ 0.6097, -1.2756, -0.0020],
         [-1.4833, -1.9792,  0.4775],
         [-0.5957,  1.0476, -0.6252]],

        [[-1.0433,  0.5797,  1.4811],
         [ 0.5857,  0.5164, -1.0622],
         [-0.6777,  0.1642, -1.1433]]], requires_grad=True)
tensor([[-0.9580, -0.2813,  1.4565],
        [ 0.5631, -1.9938,  1.0776]])
tensor([[-0.9580, -0.2813,  1.4565],
        [ 0.5631, -1.9938,  1.0776]])
